# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 10e8ae71dbbf714c119ecbda1f62ac147c93c38511ef182f270e01a753f548fdc958b74695bc57f3f6d27717ef768e629af35815c8f6261b6cd721e2c5a3a07a

test:
  secret_key_base: 519950ee6979ec91a4033ed1bd3f94faefb4cac87863e939d44c779f68ce8be243d9cf99a941be39c6c7d2693a59bc873cf2c637a8501e18bd3317b96c8d8581

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
